---
title: Content Assist
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: A sidekick for creating great content.
baseurl: ''
url: http://posty.siteleaf.net/
twitter_username: posty_sike
github_username: posty_sike
plugins:
- jekyll-feed
